"""
DB 이관 — 한 `DATABASE_URL`에서 다른 곳으로 행을 옮긴다 (SQLite → Neon).

**POS에 요청하지 않는다.** 이미 적재·검증된 데이터를 옮기는 것이므로,
12개월을 다시 수집(389요청)할 이유가 없다 — 「POS 서버 배려」 규칙에 맞다.
같은 이유로 재실행해도 안전하다 (UPSERT).

사용:
    python -m collector.migrate --from sqlite:///./data/sodam.db   # --to 는 .env 의 DATABASE_URL
    python -m collector.migrate --from sqlite:///./data/sodam.db --to postgresql://...
    python -m collector.migrate --from ... --verify-only           # 행 수만 대조

옮기는 순서는 외래키 의존을 따른다. `menu_sales`가 `menus.menu_id`를 참조하므로
**대리키(store_id / menu_id)를 그대로 유지해야 한다.** 그래서 대상 스키마의 IDENTITY를
`GENERATED BY DEFAULT`로 두었고, 옮긴 뒤 시퀀스를 `setval`로 맞춘다 —
그러지 않으면 다음 수집의 INSERT가 이미 쓰인 id와 충돌한다.
"""

from __future__ import annotations

import argparse
import dataclasses
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from collector.config import Settings  # noqa: E402
from collector.db import Session, apply_schema, connect, connect_readonly  # noqa: E402
from collector.db import describe_target, dialect_of  # noqa: E402
from collector.logutil import enable_utf8_output, log, section, warn  # noqa: E402

# 외래키 의존 순서. stores 가 먼저, menu_sales 는 menus 뒤.
TABLES = [
    "stores",
    "users",
    "orders",
    "daily_sales",
    "hourly_sales",
    "menus",
    "menu_sales",
    "order_cancels",
    "collection_logs",
    "raw_files",
]

# 대리키가 있는 테이블 → 옮긴 뒤 시퀀스를 맞춰야 한다
IDENTITY_COLUMNS = {
    "stores": "store_id",
    "users": "user_id",
    "menus": "menu_id",
    "collection_logs": "log_id",
    "raw_files": "raw_id",
}

# SQLite 는 0/1 로, PostgreSQL 은 BOOLEAN 으로 들고 있다
BOOLEAN_COLUMNS = {
    "daily_sales": ("is_closed",),
    "menus": ("is_active",),
}

BATCH = 1_000


def columns_of(session: Session, table: str) -> list[str]:
    """대상 테이블의 컬럼 이름. 원본이 아니라 **대상** 기준으로 맞춘다."""
    if session.dialect.is_postgres:
        rows = session.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = ? ORDER BY ordinal_position",
            (table,),
        ).fetchall()
        return [row["column_name"] for row in rows]
    rows = session.execute(f"PRAGMA table_info({table})").fetchall()
    return [row["name"] for row in rows]


def read_rows(source: Session, table: str, columns: list[str]) -> list[tuple]:
    selected = ", ".join(columns)
    return [
        tuple(row[column] for column in columns)
        for row in source.execute(f"SELECT {selected} FROM {table}").fetchall()
    ]


def coerce(table: str, columns: list[str], rows: list[tuple], to_boolean: bool) -> list[tuple]:
    """
    불리언 컬럼의 표현을 대상 방언에 맞춘다.
    PostgreSQL 은 BOOLEAN 컬럼에 0/1 을 받지 않는다.
    """
    flags = BOOLEAN_COLUMNS.get(table, ())
    positions = [columns.index(name) for name in flags if name in columns]
    if not positions:
        return rows

    converted = []
    for row in rows:
        values = list(row)
        for position in positions:
            value = values[position]
            values[position] = (bool(value) if to_boolean
                                else (None if value is None else int(bool(value))))
        converted.append(tuple(values))
    return converted


def write_rows(target: Session, table: str, columns: list[str], rows: list[tuple]) -> int:
    """
    기존 행이 있으면 건너뛴다 (`DO NOTHING`) — 재실행해도 안전하다.
    `raw_files` 는 대리키만 있고 자연키가 없어 중복이 쌓일 수 있으므로 미리 비운다.
    """
    if not rows:
        return 0
    names = ", ".join(columns)
    marks = ",".join("?" * len(columns))
    statement = f"INSERT INTO {table} ({names}) VALUES ({marks}) ON CONFLICT DO NOTHING"

    for start in range(0, len(rows), BATCH):
        target.executemany(statement, rows[start:start + BATCH])
    return len(rows)


def resync_identity(target: Session, table: str) -> None:
    """
    다음 INSERT가 이미 쓰인 id를 다시 발급하지 않게 시퀀스를 올린다.
    이 단계를 빠뜨리면 첫 수집에서 곧바로 중복키 오류가 난다.
    """
    column = IDENTITY_COLUMNS.get(table)
    if column is None or not target.dialect.is_postgres:
        return
    target.execute(
        f"SELECT setval(pg_get_serial_sequence('{table}', '{column}'), "
        f"COALESCE((SELECT MAX({column}) FROM {table}), 1))"
    )


def count(session: Session, table: str) -> int:
    return int(session.execute(f"SELECT COUNT(*) AS n FROM {table}").fetchone()["n"])


def migrate(source_settings: Settings, target_settings: Settings, verify_only: bool) -> int:
    section("DB 이관")
    log(f"  원본: {describe_target(source_settings)}")
    log(f"  대상: {describe_target(target_settings)}")

    if source_settings.database_url == target_settings.database_url:
        warn("원본과 대상이 같습니다.")
        return 2

    mismatches: list[str] = []
    with connect_readonly(source_settings) as source, connect(target_settings) as target:
        if not verify_only:
            apply_schema(target)

        to_boolean = target.dialect.is_postgres
        for table in TABLES:
            columns = columns_of(target, table)
            source_columns = columns_of(source, table)
            missing = [c for c in columns if c not in source_columns]
            if missing:
                warn(f"  {table}: 원본에 없는 컬럼 {missing} — 건너뜁니다")
                mismatches.append(table)
                continue

            if verify_only:
                before, after = count(source, table), count(target, table)
                mark = "=" if before == after else "≠"
                log(f"  {table:18} 원본 {before:>7,} {mark} 대상 {after:>7,}")
                if before != after:
                    mismatches.append(table)
                continue

            if table == "raw_files":
                target.execute("DELETE FROM raw_files")   # 자연키가 없어 중복이 쌓인다

            rows = coerce(table, columns, read_rows(source, table, columns), to_boolean)
            write_rows(target, table, columns, rows)
            resync_identity(target, table)

            moved, total = len(rows), count(target, table)
            log(f"  {table:18} {moved:>7,}행 읽음 → 대상 {total:>7,}행")
            if total < moved:
                mismatches.append(table)

    if mismatches:
        warn(f"\n  대조 불일치: {', '.join(mismatches)}")
        return 2
    log("\n  모든 테이블 일치")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="DB 이관 (POS 요청 없음)")
    parser.add_argument("--from", dest="source", required=True,
                        help="원본 DATABASE_URL (예: sqlite:///./data/sodam.db)")
    parser.add_argument("--to", dest="target",
                        help="대상 DATABASE_URL (기본: .env 의 DATABASE_URL)")
    parser.add_argument("--verify-only", action="store_true",
                        help="옮기지 않고 행 수만 대조")
    return parser.parse_args()


def main() -> int:
    enable_utf8_output()
    args = parse_args()
    base = Settings.load()

    source = dataclasses.replace(base, database_url=args.source)
    target = dataclasses.replace(base, database_url=args.target) if args.target else base

    for settings in (source, target):
        dialect_of(settings)        # 해석 불가한 URL 이면 여기서 바로 실패한다

    return migrate(source, target, args.verify_only)


if __name__ == "__main__":
    raise SystemExit(main())
